# coding: utf-8

"""
    

    # Authentication For more information on authorization and gaining an access/refresh token, please visit: [Authentication](/docs/fundamentals/authentication/auth-overview). <SecurityDefinitions /> 

    The version of the OpenAPI document: 
    Contact: ClientServices@tradestation.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictStr

class ActivationTrigger(BaseModel):
    """
    The trigger type allows you to specify the type of tick, number, and pattern of ticks that will trigger a specific row of an activation rule.
    """
    key: Optional[StrictStr] = Field(None, alias="Key", description="Value used in the `TriggerKey` property of `MarketActivationRules` in the `AdvancedOptions` for an order. Valid Values are: `STT`, `STTN`, `SBA`, `SAB`, `DTT`, `DTTN`, `DBA`, `DAB`, `TTT`, `TTTN`, `TBA`, and `TAB`.")
    name: Optional[StrictStr] = Field(None, alias="Name")
    description: Optional[StrictStr] = Field(None, alias="Description")
    __properties = ["Key", "Name", "Description"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ActivationTrigger:
        """Create an instance of ActivationTrigger from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ActivationTrigger:
        """Create an instance of ActivationTrigger from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ActivationTrigger.parse_obj(obj)

        _obj = ActivationTrigger.parse_obj({
            "key": obj.get("Key"),
            "name": obj.get("Name"),
            "description": obj.get("Description")
        })
        return _obj


