# coding: utf-8

"""
    

    # Authentication For more information on authorization and gaining an access/refresh token, please visit: [Authentication](/docs/fundamentals/authentication/auth-overview). <SecurityDefinitions /> 

    The version of the OpenAPI document: 
    Contact: ClientServices@tradestation.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class AdvancedOrderType(str, Enum):
    """
    The type of the advanced order.
    """

    """
    allowed enum values
    """
    NORMAL = 'NORMAL'
    BRK = 'BRK'
    OCO = 'OCO'

    @classmethod
    def from_json(cls, json_str: str) -> AdvancedOrderType:
        """Create an instance of AdvancedOrderType from a JSON string"""
        return AdvancedOrderType(json.loads(json_str))


