# coding: utf-8

"""
    

    # Authentication For more information on authorization and gaining an access/refresh token, please visit: [Authentication](/docs/fundamentals/authentication/auth-overview). <SecurityDefinitions /> 

    The version of the OpenAPI document: 
    Contact: ClientServices@tradestation.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class AssetType(str, Enum):
    """
    The type of financial instrument that a symbol represents.
    """

    """
    allowed enum values
    """
    UNKNOWN = 'UNKNOWN'
    STOCK = 'STOCK'
    STOCKOPTION = 'STOCKOPTION'
    FUTURE = 'FUTURE'
    FUTUREOPTION = 'FUTUREOPTION'
    FOREX = 'FOREX'
    CURRENCYOPTION = 'CURRENCYOPTION'
    INDEX = 'INDEX'
    INDEXOPTION = 'INDEXOPTION'
    MUTUALFUND = 'MUTUALFUND'
    MONEYMARKETFUND = 'MONEYMARKETFUND'
    BOND = 'BOND'
    CRYPTO = 'CRYPTO'

    @classmethod
    def from_json(cls, json_str: str) -> AssetType:
        """Create an instance of AssetType from a JSON string"""
        return AssetType(json.loads(json_str))


