# coding: utf-8

"""
    

    # Authentication For more information on authorization and gaining an access/refresh token, please visit: [Authentication](/docs/fundamentals/authentication/auth-overview). <SecurityDefinitions /> 

    The version of the OpenAPI document: 
    Contact: ClientServices@tradestation.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import Optional
from pydantic import BaseModel, Field, StrictStr

class Expiration1(BaseModel):
    """
    Provides information about an option contract expiration.
    """
    var_date: Optional[datetime] = Field(None, alias="Date", description="Timestamp represented as an RFC3339 formatted date, a profile of the ISO 8601 date standard. E.g. `2021-12-17T00:00:00Z`.")
    type: Optional[StrictStr] = Field(None, alias="Type", description="Expiration Type, e.g. `Weekly`, `Monthly`, `Quarterly`, `EOM`, or `Other`.")
    __properties = ["Date", "Type"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Expiration1:
        """Create an instance of Expiration1 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Expiration1:
        """Create an instance of Expiration1 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return Expiration1.parse_obj(obj)

        _obj = Expiration1.parse_obj({
            "var_date": obj.get("Date"),
            "type": obj.get("Type")
        })
        return _obj


