# coding: utf-8

"""
    

    # Authentication For more information on authorization and gaining an access/refresh token, please visit: [Authentication](/docs/fundamentals/authentication/auth-overview). <SecurityDefinitions /> 

    The version of the OpenAPI document: 
    Contact: ClientServices@tradestation.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictStr

class IncrementScheduleRow(BaseModel):
    """
    IncrementScheduleRow describes a threshold where prices above or equal to the StartsAt threshold will increment at the Increment value defined. A series of rows are provided to build a table to the IncrementSchedule() scheme option.
    """
    increment: Optional[StrictStr] = Field(None, alias="Increment", description="The incremental value.")
    starts_at: Optional[StrictStr] = Field(None, alias="StartsAt", description="The initial value to start incrementing from.")
    __properties = ["Increment", "StartsAt"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> IncrementScheduleRow:
        """Create an instance of IncrementScheduleRow from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> IncrementScheduleRow:
        """Create an instance of IncrementScheduleRow from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return IncrementScheduleRow.parse_obj(obj)

        _obj = IncrementScheduleRow.parse_obj({
            "increment": obj.get("Increment"),
            "starts_at": obj.get("StartsAt")
        })
        return _obj


