# coding: utf-8

"""
    

    # Authentication For more information on authorization and gaining an access/refresh token, please visit: [Authentication](/docs/fundamentals/authentication/auth-overview). <SecurityDefinitions /> 

    The version of the OpenAPI document: 
    Contact: ClientServices@tradestation.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class OrderType1(str, Enum):
    """
    The order type of the order.
    """

    """
    allowed enum values
    """
    LIMIT = 'Limit'
    STOPMARKET = 'StopMarket'
    MARKET = 'Market'
    STOPLIMIT = 'StopLimit'

    @classmethod
    def from_json(cls, json_str: str) -> OrderType1:
        """Create an instance of OrderType1 from a JSON string"""
        return OrderType1(json.loads(json_str))


