# coding: utf-8

"""
    

    # Authentication For more information on authorization and gaining an access/refresh token, please visit: [Authentication](/docs/fundamentals/authentication/auth-overview). <SecurityDefinitions /> 

    The version of the OpenAPI document: 
    Contact: ClientServices@tradestation.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, Dict, Optional
from pydantic import BaseModel, Field, StrictStr

class OrderConfirmResponseLeg(BaseModel):
    """
    An object that is returned from order confirm in WebAPI.
    """
    expiration_date: Optional[Dict[str, Any]] = Field(None, alias="ExpirationDate", description="Timestamp represented as an RFC3339 formatted date, a profile of the ISO 8601 date standard.  E.g. `2023-01-01T23:30:30Z`.")
    option_type: Optional[StrictStr] = Field(None, alias="OptionType", description="Defines whether an option is a call or a put. Valid values are `CALL` and `PUT`.")
    quantity: Optional[StrictStr] = Field(None, alias="Quantity", description="The quantity.")
    strike_price: Optional[StrictStr] = Field(None, alias="StrikePrice", description="The strike price for this option.")
    symbol: Optional[StrictStr] = Field(None, alias="Symbol", description="The symbol name associated with this option.")
    trade_action: Optional[StrictStr] = Field(None, alias="TradeAction", description="TradeAction represents the different trade actions that can be sent to or received from WebAPI. Conveys the intent of the trade: - `BUY` - crypto, equities and futures - `SELL` - crypto, equities and futures - `BUYTOCOVER` - equities - `SELLSHORT` - equities - `BUYTOOPEN` - options - `BUYTOCLOSE` - options - `SELLTOOPEN` - options - `SELLTOCLOSE` - options")
    __properties = ["ExpirationDate", "OptionType", "Quantity", "StrikePrice", "Symbol", "TradeAction"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> OrderConfirmResponseLeg:
        """Create an instance of OrderConfirmResponseLeg from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> OrderConfirmResponseLeg:
        """Create an instance of OrderConfirmResponseLeg from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return OrderConfirmResponseLeg.parse_obj(obj)

        _obj = OrderConfirmResponseLeg.parse_obj({
            "expiration_date": obj.get("ExpirationDate"),
            "option_type": obj.get("OptionType"),
            "quantity": obj.get("Quantity"),
            "strike_price": obj.get("StrikePrice"),
            "symbol": obj.get("Symbol"),
            "trade_action": obj.get("TradeAction")
        })
        return _obj


