# coding: utf-8

"""
    

    # Authentication For more information on authorization and gaining an access/refresh token, please visit: [Authentication](/docs/fundamentals/authentication/auth-overview). <SecurityDefinitions /> 

    The version of the OpenAPI document: 
    Contact: ClientServices@tradestation.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, conlist
from openapi_client.models.order_confirm_response import OrderConfirmResponse

class OrderConfirmResponses(BaseModel):
    """
    A collection of OrderConfirmResponse objects.
    """
    confirmations: Optional[conlist(OrderConfirmResponse)] = Field(None, alias="Confirmations")
    __properties = ["Confirmations"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> OrderConfirmResponses:
        """Create an instance of OrderConfirmResponses from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in confirmations (list)
        _items = []
        if self.confirmations:
            for _item in self.confirmations:
                if _item:
                    _items.append(_item.to_dict())
            _dict['Confirmations'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> OrderConfirmResponses:
        """Create an instance of OrderConfirmResponses from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return OrderConfirmResponses.parse_obj(obj)

        _obj = OrderConfirmResponses.parse_obj({
            "confirmations": [OrderConfirmResponse.from_dict(_item) for _item in obj.get("Confirmations")] if obj.get("Confirmations") is not None else None
        })
        return _obj


