# coding: utf-8

"""
    

    # Authentication For more information on authorization and gaining an access/refresh token, please visit: [Authentication](/docs/fundamentals/authentication/auth-overview). <SecurityDefinitions /> 

    The version of the OpenAPI document: 
    Contact: ClientServices@tradestation.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictStr, validator

class OrderConfirmRequestDefinitionLegsInner(BaseModel):
    """
    OrderConfirmRequestDefinitionLegsInner
    """
    symbol: Optional[StrictStr] = Field(None, alias="Symbol", description="Must be UPPERCASE")
    quantity: Optional[StrictStr] = Field(None, alias="Quantity")
    trade_action: Optional[StrictStr] = Field(None, alias="TradeAction", description="Conveys the intent of the trade * BUY - equity and futures trades * SELL - equity and futures trades * BUYTOCOVER - equity trade to close a short position * SELLSHORT - equity trade to open a short position * BUYTOOPEN - option trades * BUYTOCLOSE - option trades * SELLTOOPEN - option trades * SELLTOCLOSE - option trades ")
    __properties = ["Symbol", "Quantity", "TradeAction"]

    @validator('trade_action')
    def trade_action_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('BUY', 'SELL', 'BUYTOCOVER', 'SELLSHORT', 'BUYTOOPEN', 'BUYTOCLOSE', 'SELLTOOPEN', 'SELLTOCLOSE'):
            raise ValueError("must be one of enum values ('BUY', 'SELL', 'BUYTOCOVER', 'SELLSHORT', 'BUYTOOPEN', 'BUYTOCLOSE', 'SELLTOOPEN', 'SELLTOCLOSE')")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> OrderConfirmRequestDefinitionLegsInner:
        """Create an instance of OrderConfirmRequestDefinitionLegsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> OrderConfirmRequestDefinitionLegsInner:
        """Create an instance of OrderConfirmRequestDefinitionLegsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return OrderConfirmRequestDefinitionLegsInner.parse_obj(obj)

        _obj = OrderConfirmRequestDefinitionLegsInner.parse_obj({
            "symbol": obj.get("Symbol"),
            "quantity": obj.get("Quantity"),
            "trade_action": obj.get("TradeAction")
        })
        return _obj


