# coding: utf-8

"""
    

    # Authentication For more information on authorization and gaining an access/refresh token, please visit: [Authentication](/docs/fundamentals/authentication/auth-overview). <SecurityDefinitions /> 

    The version of the OpenAPI document: 
    Contact: ClientServices@tradestation.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class PositionDirection1(str, Enum):
    """
    Specifies if the position is Long or Short.
    """

    """
    allowed enum values
    """
    LONG = 'Long'
    SHORT = 'Short'

    @classmethod
    def from_json(cls, json_str: str) -> PositionDirection1:
        """Create an instance of PositionDirection1 from a JSON string"""
        return PositionDirection1(json.loads(json_str))


