# coding: utf-8

"""
    

    # Authentication For more information on authorization and gaining an access/refresh token, please visit: [Authentication](/docs/fundamentals/authentication/auth-overview). <SecurityDefinitions /> 

    The version of the OpenAPI document: 
    Contact: ClientServices@tradestation.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictBool, StrictStr

class SpreadType(BaseModel):
    """
    Provides information about a specific spread type.
    """
    name: Optional[StrictStr] = Field(None, alias="Name", description="Name of the spread type.")
    strike_interval: Optional[StrictBool] = Field(None, alias="StrikeInterval", description="A true value indicates the spread type is comprised of multiple strike prices. If this is the case, the `strikeInterval` parameter can be used with the [Get Option Chain](#operation/GetOptionChain) and [Get Option Strikes](#operation/GetOptionStrikes) endpoints to specify the interval between the strikes of a spread.")
    expiration_interval: Optional[StrictBool] = Field(None, alias="ExpirationInterval", description="Indicates whether this spread type uses multiple expirations.")
    __properties = ["Name", "StrikeInterval", "ExpirationInterval"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> SpreadType:
        """Create an instance of SpreadType from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> SpreadType:
        """Create an instance of SpreadType from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return SpreadType.parse_obj(obj)

        _obj = SpreadType.parse_obj({
            "name": obj.get("Name"),
            "strike_interval": obj.get("StrikeInterval"),
            "expiration_interval": obj.get("ExpirationInterval")
        })
        return _obj


