# coding: utf-8

"""
    

    # Authentication For more information on authorization and gaining an access/refresh token, please visit: [Authentication](/docs/fundamentals/authentication/auth-overview). <SecurityDefinitions /> 

    The version of the OpenAPI document: 
    Contact: ClientServices@tradestation.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class Status1(str, Enum):
    """
    Status defines an Status type - ACK - Received - BRO - Broken - CAN - Canceled - EXP - Expired - FLL - Filled - FLP - Partial Fill (UROut) - FPR - Partial Fill (Alive) - LAT - Too Late to Cancel - OPN - Sent - OUT - UROut - REJ - Rejected - UCH - Replaced - UCN - Cancel Sent - TSC – Trade Server Canceled - RJC – Cancel Request Rejected - DON – Queued - RSN - Replace Sent - CND – Condition Met - OSO - OSO Order - SUS - Suspended
    """

    """
    allowed enum values
    """
    ACK = 'ACK'
    BRO = 'BRO'
    CAN = 'CAN'
    EXP = 'EXP'
    FLL = 'FLL'
    FLP = 'FLP'
    FPR = 'FPR'
    LAT = 'LAT'
    OPN = 'OPN'
    OUT = 'OUT'
    REJ = 'REJ'
    UCH = 'UCH'
    UCN = 'UCN'
    TSC = 'TSC'
    RJC = 'RJC'
    DON = 'DON'
    RSN = 'RSN'
    CND = 'CND'
    OSO = 'OSO'
    SUS = 'SUS'

    @classmethod
    def from_json(cls, json_str: str) -> Status1:
        """Create an instance of Status1 from a JSON string"""
        return Status1(json.loads(json_str))


