# coding: utf-8

"""
    

    # Authentication For more information on authorization and gaining an access/refresh token, please visit: [Authentication](/docs/fundamentals/authentication/auth-overview). <SecurityDefinitions /> 

    The version of the OpenAPI document: 
    Contact: ClientServices@tradestation.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401

from typing import Any, List, Optional
from pydantic import BaseModel, Field, StrictStr, ValidationError, validator
from openapi_client.models.heartbeat2 import Heartbeat2
from openapi_client.models.market_depth_aggregate import MarketDepthAggregate
from openapi_client.models.stream_error_response import StreamErrorResponse
from typing import Union, Any, List, TYPE_CHECKING
from pydantic import StrictStr, Field

STREAMMARKETDEPTHAGGREGATES200RESPONSE_ONE_OF_SCHEMAS = ["Heartbeat2", "MarketDepthAggregate", "StreamErrorResponse"]

class StreamMarketDepthAggregates200Response(BaseModel):
    """
    StreamMarketDepthAggregates200Response
    """
    # data type: MarketDepthAggregate
    oneof_schema_1_validator: Optional[MarketDepthAggregate] = None
    # data type: Heartbeat2
    oneof_schema_2_validator: Optional[Heartbeat2] = None
    # data type: StreamErrorResponse
    oneof_schema_3_validator: Optional[StreamErrorResponse] = None
    if TYPE_CHECKING:
        actual_instance: Union[Heartbeat2, MarketDepthAggregate, StreamErrorResponse]
    else:
        actual_instance: Any
    one_of_schemas: List[str] = Field(STREAMMARKETDEPTHAGGREGATES200RESPONSE_ONE_OF_SCHEMAS, const=True)

    class Config:
        validate_assignment = True

    def __init__(self, *args, **kwargs):
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = StreamMarketDepthAggregates200Response.construct()
        error_messages = []
        match = 0
        # validate data type: MarketDepthAggregate
        if not isinstance(v, MarketDepthAggregate):
            error_messages.append(f"Error! Input type `{type(v)}` is not `MarketDepthAggregate`")
        else:
            match += 1
        # validate data type: Heartbeat2
        if not isinstance(v, Heartbeat2):
            error_messages.append(f"Error! Input type `{type(v)}` is not `Heartbeat2`")
        else:
            match += 1
        # validate data type: StreamErrorResponse
        if not isinstance(v, StreamErrorResponse):
            error_messages.append(f"Error! Input type `{type(v)}` is not `StreamErrorResponse`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in StreamMarketDepthAggregates200Response with oneOf schemas: Heartbeat2, MarketDepthAggregate, StreamErrorResponse. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in StreamMarketDepthAggregates200Response with oneOf schemas: Heartbeat2, MarketDepthAggregate, StreamErrorResponse. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: dict) -> StreamMarketDepthAggregates200Response:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> StreamMarketDepthAggregates200Response:
        """Returns the object represented by the json string"""
        instance = StreamMarketDepthAggregates200Response.construct()
        error_messages = []
        match = 0

        # deserialize data into MarketDepthAggregate
        try:
            instance.actual_instance = MarketDepthAggregate.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into Heartbeat2
        try:
            instance.actual_instance = Heartbeat2.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into StreamErrorResponse
        try:
            instance.actual_instance = StreamErrorResponse.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into StreamMarketDepthAggregates200Response with oneOf schemas: Heartbeat2, MarketDepthAggregate, StreamErrorResponse. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into StreamMarketDepthAggregates200Response with oneOf schemas: Heartbeat2, MarketDepthAggregate, StreamErrorResponse. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        to_json = getattr(self.actual_instance, "to_json", None)
        if callable(to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> dict:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        to_dict = getattr(self.actual_instance, "to_dict", None)
        if callable(to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.dict())


